// Interface text in every language. Tour content (stories, directions) lives in tours/<city>/<tour>/tour[.<lang>].json.
// {name} is replaced by t(key, {name: value}). No em dashes in any of these.
export const LANGS = { en: 'English', nl: 'Nederlands', de: 'Deutsch' };
export const SPEECH = { en: 'en-GB', nl: 'nl-NL', de: 'de-DE' }; // for the phone's own voice

export const STRINGS = {
  en: {
    loading: 'Loading tour…', loadFail: 'Could not load the tour. Check your connection and reload.',
    km: 'km', stops: 'stops', withStories: 'with stories', byBike: 'by bike', onFoot: 'on foot',
    lede: "A self-guided tour from {start} to {end}.", startName: '{title}',
    ledeTap: 'When you reach a spot, its story is ready. Tap play whenever you want to listen.',
    ledeStopped: 'When you reach a spot and stop, its story plays by itself.',
    ledeAuto: 'Each story plays by itself when you reach the spot.',
    language: 'Language', startingPoint: 'Starting point', gettingAround: 'Getting around', bike: 'By bike', walk: 'On foot',
    bonusStops: 'Bonus stops', detourAfter: 'A detour of about {km} km after stop {n}', afterLast: 'About {km} km on from the last stop',
    storiesStart: 'Stories start', modeTap: 'When I tap play', modeStopped: "Once I've stopped at the spot", modeAuto: 'As soon as I arrive',
    rideTogether: 'Ride together', groupIntro: 'One person leads. Everyone hears the same story at the same moment, and you see each other on the map.',
    yourName: 'Your name', startGroup: 'Start a group', groupCode: 'Group code', codePh: 'CODE', join: 'Join', shareCode: 'Share code', copied: 'Copied', leaveGroup: 'Leave group',
    startTour: 'Start the tour', continueTour: 'Continue the tour', testRide: 'Try a test ride from here',
    note: "Keep this page open with the screen on, and allow location access. Your phone's silent switch can mute the audio.",
    safetyBike: 'Wear one earbud at most while riding.', safetyWalk: 'Keep one ear free for traffic when crossing streets.',
    progress: '{n} of {total} stops', mapLabel: 'Route map with stops', wholeRoute: 'Whole route', aroundMe: 'Around me',
    locationOff: 'Location off', ready: 'Ready', beforeRide: 'Before you ride', play: 'Play', pause: 'Pause', playTitle: 'Play {title}',
    seek: 'Position in story', back15: 'Back 15 seconds', tellMore: 'Tell me more', tellMoreAbout: 'Tell me more about {title}', readAlong: 'Read along',
    showPhoto: 'Show the photo larger', then: 'Then', photoBy: 'Photo: {author}, {licence}', source: 'source', close: 'Close', photo: 'Photo',
    nextStop: 'Next stop', startNav: 'Start navigation', gmapsInstead: 'Open in Google Maps instead', stopsHeading: 'Stops',
    testText: 'Test ride moves you along the route on screen and waits at each stop until the story is over, just like the real thing.',
    startTest: 'Start test ride', stopTest: 'Stop test ride', speed: 'Speed {n}×',
    foot: 'Narration voice is synthetic. Route distances are from OpenStreetMap bike routing.', settings: 'Starting point and settings', reset: 'Reset tour progress', resetConfirm: 'Reset tour progress?',
    mapOffline: 'The map needs an internet connection. Stories and directions still work.',
    playStop: 'Play stop {n}, {title}', playBonus: 'Play bonus stop, {title}', bonus: 'bonus',
    allHeard: "All stops heard.", done: 'Done', next: 'Next: {n}. {title}', waitingLocation: 'Waiting for location',
    arrived: 'You have arrived · {what}', stopOf: 'Stop {n} of {total}', bonusStop: 'Bonus stop', intro: 'Introduction', finish: 'Finish',
    stopWhenSafe: 'Stop when it is safe. The story starts once you have stopped', tapToListen: 'You have arrived. Tap play to listen',
    followingLeader: 'Following the group leader', headBack: 'Head back to the route', thanks: 'Thanks for riding',
    wantMore: 'Want the longer story? Tap Tell me more', rideOn: 'Ride on to the next stop',
    readByPhone: '{what} · read by your phone', openReadAlong: '{what} · open Read along', withGroup: '{what} · with the group',
    testRideGps: 'Test ride', gpsAcc: 'GPS ±{m} m', offRoute: 'Off route', noGps: 'No GPS on this device', findingYou: 'Finding you…',
    locBlocked: 'Location blocked. Allow it in browser settings', locUnavailable: 'Location unavailable', allowLocation: 'Allow location access to navigate',
    arrivedBanner: 'Arrived', storyWhenStopped: 'The story starts once you have stopped', tapToHear: 'Tap play to hear the story',
    bonusBanner: 'Bonus stop: {title}', tourComplete: 'Tour complete', allStopsHeard: 'All stops heard',
    turnAroundBack: 'Turn around, then head back to the route', continueTo: 'Then continue to {n}. {title}',
    headTo: 'Head to {n}. {title}', dottedLine: 'Follow the dotted line to your first stop',
    thenStep: 'Then {step}', thenArrive: 'Then arrive at {n}. {title}', arriveAt: 'Arrive at {n}. {title}',
    thenSplit: ', (?:then|and) ', navIntro: 'Directions to the next stop. ',
    bonusShort: 'Bonus: {title}', eta: '{dist} · {min} min · arrive {time}', etaShort: '{dist} · {min} min', directions: 'Directions',
    recenter: 'Re-center', overview: 'Overview', skipBonus: 'Skip bonus',
    hours: '~{n} h', minutes: '~{n} min', min: 'min',
    groupNoCode: 'No group with that code. Check the letters with your group leader.', groupFail: 'Could not join the group. Try again.', groupBadCode: 'A group code is four letters.',
    connecting: 'Connecting…', youLead: 'You lead · {n} {riders} with you', rider: 'rider', riders: 'riders', following: 'Following {name} · {n} riders', theLeader: 'the leader',
    groupReconnecting: 'Group {code} · reconnecting…', groupYouLead: 'Group {code} · you lead · {n} online', groupFollowing: 'Group {code} · following {name} · {n} online',
    leads: '{name} (leads)', shareText: "Join me on {tour}. Group code {code}",
    downloading: 'Downloading tour for offline use: {p}%', downloaded: 'Tour downloaded, ready offline', downloadLater: 'Tour not fully downloaded yet. It will finish next time you are online.',
    mediaAlbum: "Audio tour",
    farTitle: "You are not in {city} yet",
    farSub: "Navigation starts near the route. Try a test ride meanwhile.",
    homeKicker: "Self-guided audio tour",
    settingsTitle: "Settings",
    back: "Back",
    chooseTour: "Choose your tour",
    moreTours: "More tours are on the way.",
    comingSoon: "Coming soon", cityLbl: "City",
    city_berlin: "Berlin", city_amsterdam: "Amsterdam", city_london: "London", city_paris: "Paris", city_rome: "Rome", city_barcelona: "Barcelona",
    tourStops: "Tour stops",
    storyLen: "{t} story",
    skippedTag: "skipped",
    nextTag: "Next",
    groupRide: "Group ride",
    orJoin: "or join with a code",
    shareThisCode: "Share this code",
    ridersJoined: "Riders",
    leaderTag: "Leader",
    youTag: "You",
    awayTag: "Offline",
    current: "Current",
    nextLbl: "Next",
    playStory: "Play story",
    resume: "Resume",
    storyBtn: "Story",
    backToRoute: "Back to route",
    offFrom: "{d} from the route",
    offThen: "Then continue to",
    offPill: "{d} off route",
    now: "Now",
    fwd15: "Forward 15 seconds",
    completeTitle: "Tour complete!",
    completeRide: "You have ridden {tour}",
    completeWalk: "You have walked {tour}",
    distance: "Distance",
    rideTime: "Time",
    storiesLbl: "Stories",
    rate: "Rate this tour",
    rateSub: "How was your experience?",
    rateThanks: "Thanks for rating",
    shareRide: "Share your ride",
    shareRideText: "I just did {tour}, a self-guided audio tour: {km} km and {n} stories.",
    backHome: "Back to home",
    tourMode: "Tour mode",
    cycling: "Cycling",
    walking: "Walking",
    storySettings: "Story settings",
    autoPlay: "Auto-play stories",
    autoPlaySub: "Start at each stop by themselves",
    onlyStopped: "Only start stories when stopped",
    onlyStoppedSub: "Waits until you have stopped for 5 seconds",
    voiceSpeed: "Voice speed",
    speedSlow: "Slow",
    speedNormal: "Normal",
    speedFaster: "Slightly faster",
    speedFast: "Fast",
    offlineTitle: "Offline",
    offlineRow: "Tour for offline use",
    tourLabel: "Tour",
    tabHome: "Home",
    tabTours: "Tours",
    away: "{dist} away",
    toStart: "To the start",
    progressLbl: "Stories heard",
    startShort: "Start",
    ridden: "{d} ridden",
    walked: "{d} walked",
    stopChip: "Stop {n}/{total}",
    awayUnit: "{unit} away",
    offlineReady: "Offline",
  },
  nl: {
    loading: 'Tour laden…', loadFail: 'De tour kon niet worden geladen. Controleer je verbinding en herlaad de pagina.',
    km: 'km', stops: 'stops', withStories: 'met verhalen', byBike: 'op de fiets', onFoot: 'te voet',
    lede: "Een tour op eigen gelegenheid, van {start} naar {end}.", startName: '{title}',
    ledeTap: 'Als je bij een plek bent, staat het verhaal klaar. Tik op afspelen wanneer je wilt luisteren.',
    ledeStopped: 'Als je bij een plek bent en stopt, begint het verhaal vanzelf.',
    ledeAuto: 'Elk verhaal begint vanzelf als je bij de plek aankomt.',
    language: 'Taal', startingPoint: 'Startpunt', gettingAround: 'Hoe ga je', bike: 'Op de fiets', walk: 'Te voet',
    bonusStops: 'Extra stops', detourAfter: 'Een omweg van ongeveer {km} km na stop {n}', afterLast: 'Ongeveer {km} km verder dan de laatste stop',
    storiesStart: 'Verhalen beginnen', modeTap: 'Als ik op afspelen tik', modeStopped: 'Als ik bij de plek ben gestopt', modeAuto: 'Zodra ik aankom',
    rideTogether: 'Samen fietsen', groupIntro: 'Eén persoon leidt. Iedereen hoort hetzelfde verhaal op hetzelfde moment, en je ziet elkaar op de kaart.',
    yourName: 'Je naam', startGroup: 'Groep starten', groupCode: 'Groepscode', codePh: 'CODE', join: 'Meedoen', shareCode: 'Code delen', copied: 'Gekopieerd', leaveGroup: 'Groep verlaten',
    startTour: 'Start de tour', continueTour: 'Ga verder met de tour', testRide: 'Probeer een testrit vanaf hier',
    note: 'Houd deze pagina open met het scherm aan, en sta locatietoegang toe. De stille modus van je telefoon kan het geluid dempen.',
    safetyBike: 'Draag onder het fietsen hooguit één oordopje.', safetyWalk: 'Houd bij het oversteken één oor vrij voor het verkeer.',
    progress: '{n} van {total} stops', mapLabel: 'Routekaart met stops', wholeRoute: 'Hele route', aroundMe: 'Om mij heen',
    locationOff: 'Locatie uit', ready: 'Klaar', beforeRide: 'Voordat je vertrekt', play: 'Afspelen', pause: 'Pauze', playTitle: '{title} afspelen',
    seek: 'Positie in verhaal', back15: '15 seconden terug', tellMore: 'Vertel meer', tellMoreAbout: 'Vertel meer over {title}', readAlong: 'Meelezen',
    showPhoto: 'Foto groter tonen', then: 'Toen', photoBy: 'Foto: {author}, {licence}', source: 'bron', close: 'Sluiten', photo: 'Foto',
    nextStop: 'Volgende stop', startNav: 'Navigatie starten', gmapsInstead: 'Open in Google Maps', stopsHeading: 'Stops',
    testText: 'Een testrit beweegt je op het scherm langs de route en wacht bij elke stop tot het verhaal voorbij is, net als in het echt.',
    startTest: 'Testrit starten', stopTest: 'Testrit stoppen', speed: 'Snelheid {n}×',
    foot: 'De stem is synthetisch. Afstanden komen uit de fietsrouteplanning van OpenStreetMap.', settings: 'Startpunt en instellingen', reset: 'Voortgang wissen', resetConfirm: 'Voortgang van de tour wissen?',
    mapOffline: 'De kaart heeft internet nodig. Verhalen en aanwijzingen werken gewoon.',
    playStop: 'Stop {n} afspelen, {title}', playBonus: 'Extra stop afspelen, {title}', bonus: 'extra',
    allHeard: "Alle stops gehoord.", done: 'Klaar', next: 'Volgende: {n}. {title}', waitingLocation: 'Wachten op locatie',
    arrived: 'Je bent er · {what}', stopOf: 'Stop {n} van {total}', bonusStop: 'Extra stop', intro: 'Inleiding', finish: 'Einde',
    stopWhenSafe: 'Stop als het veilig kan. Het verhaal begint zodra je stilstaat', tapToListen: 'Je bent er. Tik op afspelen om te luisteren',
    followingLeader: 'Je volgt de groepsleider', headBack: 'Terug naar de route', thanks: 'Bedankt voor het meefietsen',
    wantMore: 'Wil je het langere verhaal? Tik op Vertel meer', rideOn: 'Fiets door naar de volgende stop',
    readByPhone: '{what} · voorgelezen door je telefoon', openReadAlong: '{what} · open Meelezen', withGroup: '{what} · met de groep',
    testRideGps: 'Testrit', gpsAcc: 'GPS ±{m} m', offRoute: 'Van de route af', noGps: 'Geen GPS op dit apparaat', findingYou: 'Locatie zoeken…',
    locBlocked: 'Locatie geblokkeerd. Sta het toe in de browserinstellingen', locUnavailable: 'Locatie niet beschikbaar', allowLocation: 'Sta locatietoegang toe om te navigeren',
    arrivedBanner: 'Aangekomen', storyWhenStopped: 'Het verhaal begint zodra je stilstaat', tapToHear: 'Tik op afspelen voor het verhaal',
    bonusBanner: 'Extra stop: {title}', tourComplete: 'Tour voltooid', allStopsHeard: 'Alle stops gehoord',
    turnAroundBack: 'Keer om en ga terug naar de route', continueTo: 'Daarna verder naar {n}. {title}',
    headTo: 'Ga naar {n}. {title}', dottedLine: 'Volg de stippellijn naar je eerste stop',
    thenStep: 'Daarna {step}', thenArrive: 'Daarna aankomst bij {n}. {title}', arriveAt: 'Aankomst bij {n}. {title}',
    thenSplit: ', daarna | en ongeveer ', navIntro: 'Route naar de volgende stop. ',
    bonusShort: 'Extra: {title}', eta: '{dist} · {min} min · aankomst {time}', etaShort: '{dist} · {min} min', directions: 'Route',
    recenter: 'Centreren', overview: 'Overzicht', skipBonus: 'Extra overslaan',
    hours: '~{n} u', minutes: '~{n} min', min: 'min',
    groupNoCode: 'Geen groep met die code. Controleer de letters bij je groepsleider.', groupFail: 'Meedoen met de groep lukte niet. Probeer het opnieuw.', groupBadCode: 'Een groepscode bestaat uit vier letters.',
    connecting: 'Verbinden…', youLead: 'Jij leidt · {n} {riders} met je mee', rider: 'fietser', riders: 'fietsers', following: 'Je volgt {name} · {n} fietsers', theLeader: 'de leider',
    groupReconnecting: 'Groep {code} · opnieuw verbinden…', groupYouLead: 'Groep {code} · jij leidt · {n} online', groupFollowing: 'Groep {code} · je volgt {name} · {n} online',
    leads: '{name} (leidt)', shareText: "Doe mee met {tour}. Groepscode {code}",
    downloading: 'Tour downloaden voor offline gebruik: {p}%', downloaded: 'Tour gedownload, klaar voor offline', downloadLater: 'Tour nog niet helemaal gedownload. Dat gaat verder zodra je weer online bent.',
    mediaAlbum: "Audiotour",
    farTitle: "Je bent nog niet in {city}",
    farSub: "De navigatie begint bij de route. Probeer intussen een testrit.",
    homeKicker: "Audiotour op eigen gelegenheid",
    settingsTitle: "Instellingen",
    back: "Terug",
    chooseTour: "Kies je tour",
    moreTours: "Er komen meer tours aan.",
    comingSoon: "Binnenkort", cityLbl: "Stad",
    city_berlin: "Berlijn", city_amsterdam: "Amsterdam", city_london: "Londen", city_paris: "Parijs", city_rome: "Rome", city_barcelona: "Barcelona",
    tourStops: "Stops van de tour",
    storyLen: "verhaal van {t}",
    skippedTag: "overgeslagen",
    nextTag: "Volgende",
    groupRide: "Groepsrit",
    orJoin: "of doe mee met een code",
    shareThisCode: "Deel deze code",
    ridersJoined: "Fietsers",
    leaderTag: "Leider",
    youTag: "Jij",
    awayTag: "Offline",
    current: "Nu",
    nextLbl: "Volgende",
    playStory: "Verhaal afspelen",
    resume: "Verder",
    storyBtn: "Verhaal",
    backToRoute: "Terug naar de route",
    offFrom: "{d} van de route",
    offThen: "Daarna verder naar",
    offPill: "{d} van de route af",
    now: "Nu",
    fwd15: "15 seconden vooruit",
    completeTitle: "Tour voltooid!",
    completeRide: "Je hebt {tour} gefietst",
    completeWalk: "Je hebt {tour} gelopen",
    distance: "Afstand",
    rideTime: "Tijd",
    storiesLbl: "Verhalen",
    rate: "Beoordeel deze tour",
    rateSub: "Hoe vond je het?",
    rateThanks: "Bedankt voor je beoordeling",
    shareRide: "Deel je rit",
    shareRideText: "Ik heb net {tour} gedaan, een audiotour op eigen gelegenheid: {km} km en {n} verhalen.",
    backHome: "Terug naar het begin",
    tourMode: "Tourmodus",
    cycling: "Fietsen",
    walking: "Wandelen",
    storySettings: "Verhalen",
    autoPlay: "Verhalen vanzelf afspelen",
    autoPlaySub: "Beginnen vanzelf bij elke stop",
    onlyStopped: "Alleen beginnen als ik stilsta",
    onlyStoppedSub: "Wacht tot je 5 seconden stilstaat",
    voiceSpeed: "Spreeksnelheid",
    speedSlow: "Langzaam",
    speedNormal: "Normaal",
    speedFaster: "Iets sneller",
    speedFast: "Snel",
    offlineTitle: "Offline",
    offlineRow: "Tour voor offline gebruik",
    tourLabel: "Tour",
    tabHome: "Start",
    tabTours: "Tours",
    away: "op {dist}",
    toStart: "Naar de start",
    progressLbl: "Verhalen gehoord",
    startShort: "Start",
    ridden: "{d} gefietst",
    walked: "{d} gelopen",
    stopChip: "Stop {n}/{total}",
    awayUnit: "{unit} verderop",
    offlineReady: "Offline",
  },
  de: {
    loading: 'Tour wird geladen…', loadFail: 'Die Tour konnte nicht geladen werden. Prüfe deine Verbindung und lade die Seite neu.',
    km: 'km', stops: 'Stationen', withStories: 'mit Geschichten', byBike: 'mit dem Rad', onFoot: 'zu Fuß',
    lede: "Eine Tour auf eigene Faust. Start: {start}, Ziel: {end}.", startName: '{title}',
    ledeTap: 'Wenn du an einem Ort ankommst, liegt seine Geschichte bereit. Tippe auf Abspielen, wann immer du zuhören willst.',
    ledeStopped: 'Wenn du an einem Ort ankommst und anhältst, startet seine Geschichte von selbst.',
    ledeAuto: 'Jede Geschichte startet von selbst, wenn du am Ort ankommst.',
    language: 'Sprache', startingPoint: 'Startpunkt', gettingAround: 'Unterwegs', bike: 'Mit dem Rad', walk: 'Zu Fuß',
    bonusStops: 'Zusatzstationen', detourAfter: 'Ein Umweg von etwa {km} km nach Station {n}', afterLast: 'Etwa {km} km weiter als die letzte Station',
    storiesStart: 'Geschichten starten', modeTap: 'Wenn ich auf Abspielen tippe', modeStopped: 'Wenn ich am Ort angehalten habe', modeAuto: 'Sobald ich ankomme',
    rideTogether: 'Gemeinsam fahren', groupIntro: 'Eine Person führt. Alle hören dieselbe Geschichte im selben Moment, und ihr seht euch gegenseitig auf der Karte.',
    yourName: 'Dein Name', startGroup: 'Gruppe starten', groupCode: 'Gruppencode', codePh: 'CODE', join: 'Beitreten', shareCode: 'Code teilen', copied: 'Kopiert', leaveGroup: 'Gruppe verlassen',
    startTour: 'Tour starten', continueTour: 'Tour fortsetzen', testRide: 'Testfahrt von hier ausprobieren',
    note: 'Lass diese Seite mit eingeschaltetem Bildschirm offen und erlaube den Standortzugriff. Der Stummschalter deines Handys kann den Ton ausschalten.',
    safetyBike: 'Trag beim Fahren höchstens einen Ohrhörer.', safetyWalk: 'Lass beim Überqueren von Straßen ein Ohr frei für den Verkehr.',
    progress: '{n} von {total} Stationen', mapLabel: 'Routenkarte mit Stationen', wholeRoute: 'Ganze Route', aroundMe: 'Um mich herum',
    locationOff: 'Standort aus', ready: 'Bereit', beforeRide: 'Bevor es losgeht', play: 'Abspielen', pause: 'Pause', playTitle: '{title} abspielen',
    seek: 'Position in der Geschichte', back15: '15 Sekunden zurück', tellMore: 'Mehr dazu', tellMoreAbout: 'Mehr dazu: {title}', readAlong: 'Mitlesen',
    showPhoto: 'Foto größer zeigen', then: 'Damals', photoBy: 'Foto: {author}, {licence}', source: 'Quelle', close: 'Schließen', photo: 'Foto',
    nextStop: 'Nächste Station', startNav: 'Navigation starten', gmapsInstead: 'In Google Maps öffnen', stopsHeading: 'Stationen',
    testText: 'Die Testfahrt bewegt dich auf dem Bildschirm die Route entlang und wartet an jeder Station, bis die Geschichte zu Ende ist, genau wie in echt.',
    startTest: 'Testfahrt starten', stopTest: 'Testfahrt beenden', speed: 'Tempo {n}×',
    foot: 'Die Stimme ist synthetisch. Die Entfernungen stammen aus der Fahrradroutenplanung von OpenStreetMap.', settings: 'Startpunkt und Einstellungen', reset: 'Fortschritt zurücksetzen', resetConfirm: 'Fortschritt der Tour zurücksetzen?',
    mapOffline: 'Die Karte braucht eine Internetverbindung. Geschichten und Wegbeschreibung funktionieren trotzdem.',
    playStop: 'Station {n} abspielen, {title}', playBonus: 'Zusatzstation abspielen, {title}', bonus: 'Zusatz',
    allHeard: "Alle Stationen gehört.", done: 'Fertig', next: 'Nächste: {n}. {title}', waitingLocation: 'Warte auf Standort',
    arrived: 'Du bist angekommen · {what}', stopOf: 'Station {n} von {total}', bonusStop: 'Zusatzstation', intro: 'Einführung', finish: 'Ende',
    stopWhenSafe: 'Halte an, wenn es sicher ist. Die Geschichte startet, sobald du stehst', tapToListen: 'Du bist angekommen. Tippe auf Abspielen, um zuzuhören',
    followingLeader: 'Du folgst der Gruppenleitung', headBack: 'Zurück zur Route', thanks: 'Danke fürs Mitfahren',
    wantMore: 'Lust auf die längere Geschichte? Tippe auf Mehr dazu', rideOn: 'Weiter zur nächsten Station',
    readByPhone: '{what} · vorgelesen von deinem Handy', openReadAlong: '{what} · Mitlesen öffnen', withGroup: '{what} · mit der Gruppe',
    testRideGps: 'Testfahrt', gpsAcc: 'GPS ±{m} m', offRoute: 'Nicht auf der Route', noGps: 'Kein GPS auf diesem Gerät', findingYou: 'Standort wird gesucht…',
    locBlocked: 'Standort blockiert. Erlaube ihn in den Browsereinstellungen', locUnavailable: 'Standort nicht verfügbar', allowLocation: 'Erlaube den Standortzugriff, um zu navigieren',
    arrivedBanner: 'Angekommen', storyWhenStopped: 'Die Geschichte startet, sobald du stehst', tapToHear: 'Tippe auf Abspielen für die Geschichte',
    bonusBanner: 'Zusatzstation: {title}', tourComplete: 'Tour beendet', allStopsHeard: 'Alle Stationen gehört',
    turnAroundBack: 'Wenden und zurück zur Route', continueTo: 'Dann weiter zu {n}. {title}',
    headTo: 'Fahr zu {n}. {title}', dottedLine: 'Folge der gepunkteten Linie zu deiner ersten Station',
    thenStep: 'Dann {step}', thenArrive: 'Dann Ankunft an {n}. {title}', arriveAt: 'Ankunft an {n}. {title}',
    thenSplit: ', dann | und etwa ', navIntro: 'Wegbeschreibung zur nächsten Station. ',
    bonusShort: 'Zusatz: {title}', eta: '{dist} · {min} Min. · Ankunft {time}', etaShort: '{dist} · {min} Min.', directions: 'Route',
    recenter: 'Zentrieren', overview: 'Übersicht', skipBonus: 'Zusatz überspringen',
    hours: '~{n} Std.', minutes: '~{n} Min.', min: 'Min.',
    groupNoCode: 'Keine Gruppe mit diesem Code. Prüf die Buchstaben mit deiner Gruppenleitung.', groupFail: 'Beitritt zur Gruppe fehlgeschlagen. Versuch es noch einmal.', groupBadCode: 'Ein Gruppencode hat vier Buchstaben.',
    connecting: 'Verbinden…', youLead: 'Du führst · {n} {riders} dabei', rider: 'Person', riders: 'Personen', following: 'Du folgst {name} · {n} Personen', theLeader: 'der Leitung',
    groupReconnecting: 'Gruppe {code} · neu verbinden…', groupYouLead: 'Gruppe {code} · du führst · {n} online', groupFollowing: 'Gruppe {code} · du folgst {name} · {n} online',
    leads: '{name} (führt)', shareText: "Mach {tour} mit mir. Gruppencode {code}",
    downloading: 'Tour wird für die Offline-Nutzung geladen: {p} %', downloaded: 'Tour geladen, offline bereit', downloadLater: 'Tour noch nicht vollständig geladen. Das geht weiter, sobald du wieder online bist.',
    mediaAlbum: "Audiotour",
    farTitle: "Du bist noch nicht in {city}",
    farSub: "Die Navigation beginnt an der Route. Probier solange eine Testfahrt.",
    homeKicker: "Audiotour auf eigene Faust",
    settingsTitle: "Einstellungen",
    back: "Zurück",
    chooseTour: "Wähle deine Tour",
    moreTours: "Weitere Touren sind in Arbeit.",
    comingSoon: "Demnächst", cityLbl: "Stadt",
    city_berlin: "Berlin", city_amsterdam: "Amsterdam", city_london: "London", city_paris: "Paris", city_rome: "Rom", city_barcelona: "Barcelona",
    tourStops: "Stationen der Tour",
    storyLen: "Geschichte, {t}",
    skippedTag: "übersprungen",
    nextTag: "Nächste",
    groupRide: "Gruppenfahrt",
    orJoin: "oder mit einem Code beitreten",
    shareThisCode: "Teile diesen Code",
    ridersJoined: "Mitfahrende",
    leaderTag: "Leitung",
    youTag: "Du",
    awayTag: "Offline",
    current: "Aktuell",
    nextLbl: "Danach",
    playStory: "Geschichte abspielen",
    resume: "Weiter",
    storyBtn: "Geschichte",
    backToRoute: "Zurück zur Route",
    offFrom: "{d} von der Route entfernt",
    offThen: "Dann weiter zu",
    offPill: "{d} neben der Route",
    now: "Heute",
    fwd15: "15 Sekunden vor",
    completeTitle: "Tour geschafft!",
    completeRide: "Du bist {tour} gefahren",
    completeWalk: "Du bist {tour} gelaufen",
    distance: "Strecke",
    rideTime: "Zeit",
    storiesLbl: "Geschichten",
    rate: "Bewerte diese Tour",
    rateSub: "Wie hat es dir gefallen?",
    rateThanks: "Danke für deine Bewertung",
    shareRide: "Teile deine Fahrt",
    shareRideText: "Ich habe gerade {tour} gemacht, eine Audiotour auf eigene Faust: {km} km und {n} Geschichten.",
    backHome: "Zurück zum Start",
    tourMode: "Tourmodus",
    cycling: "Radfahren",
    walking: "Zu Fuß",
    storySettings: "Geschichten",
    autoPlay: "Geschichten automatisch abspielen",
    autoPlaySub: "Starten an jeder Station von selbst",
    onlyStopped: "Nur starten, wenn ich stehe",
    onlyStoppedSub: "Wartet, bis du 5 Sekunden stehst",
    voiceSpeed: "Sprechtempo",
    speedSlow: "Langsam",
    speedNormal: "Normal",
    speedFaster: "Etwas schneller",
    speedFast: "Schnell",
    offlineTitle: "Offline",
    offlineRow: "Tour für die Offline-Nutzung",
    tourLabel: "Tour",
    tabHome: "Start",
    tabTours: "Touren",
    away: "{dist} entfernt",
    toStart: "Zum Start",
    progressLbl: "Geschichten gehört",
    startShort: "Start",
    ridden: "{d} gefahren",
    walked: "{d} gelaufen",
    stopChip: "Station {n}/{total}",
    awayUnit: "{unit} entfernt",
    offlineReady: "Offline",
  },
};
